In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Problem 1: Employee Salary Analysis

# Load the dataset
df = pd.read_csv("employees_large.csv")

# Compute the average salary for each department
average_salaries = df.groupby("Department")["Salary"].mean()

# Identify and print the department with the highest average salary
highest_salary_department = average_salaries.idxmax()

print("Average salaries by department:")
print(average_salaries)
print(f"Department with highest average salary: {highest_salary_department}")

Average salaries by department:
Department
Engineering    125000.0
Finance         78000.0
HR              68000.0
IT              57750.0
Marketing       43750.0
Name: Salary, dtype: float64
Department with highest average salary: Engineering

In [ ]:
#Problem 2: Sales Analysis Using Pandas


# Load the dataset
df = pd.read_csv("sales_large.csv")

# Compute the total sales for each product in each region
total_sales = df.groupby(["Region", "Product"])["Sales"].sum()

# Identify and print the product with the highest total sales across all regions
highest_selling_product = df.groupby("Product")["Sales"].sum().idxmax()

print("Total sales for each product in each region:")
print(total_sales)
print(f"Product with highest total sales: {highest_selling_product}")

Total sales for each product in each region:
Region   Product
Central  Apples      9000
         Oranges     8000
East     Apples      5000
         Bananas     8500
         Oranges    13900
North    Apples      7200
         Bananas     9000
         Oranges     4900
South    Apples     12900
         Bananas     5100
         Oranges     3000
West     Apples     18900
         Bananas    14700
         Oranges     7500
Name: Sales, dtype: int64
Product with highest total sales: Apples

In [ ]:
#Problem 3: Matrix Operations Using NumPy

In [ ]:

# Define matrices A and B
A = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B = np.array([[8, 5, 2], [7, 4, 1], [6, 3, 0]])

# Perform matrix operations
sum_matrix = A + B
difference_matrix = A - B
product_matrix = A * B

print("Sum of matrices:\n", sum_matrix)
print("Difference of matrices:\n", difference_matrix)
print("Element-wise product of matrices:\n", product_matrix)

Sum of matrices:
 [[10  9  8]
 [ 8  7  6]
 [13 12 11]]
Difference of matrices:
 [[-6 -1  4]
 [-6 -1  4]
 [ 1  6 11]]
Element-wise product of matrices:
 [[16 20 12]
 [ 7 12  5]
 [42 27  0]]

In [ ]:
#Problem 4: Statistical Analysis of a NumPy Array

# Generate a NumPy array of 10,000 random real-valued numbers
data = np.random.randn(10000)

# Compute mean and standard deviation
mean_value = np.mean(data)
std_dev = np.std(data)

# Normalize the data (scaling to range [0,1])
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))

# Count how many values are greater than the mean
greater_than_mean_count = np.sum(data > mean_value)

print("Mean of the dataset:", mean_value)
print("Standard deviation of the dataset:", std_dev)
print("Number of values greater than the mean:", greater_than_mean_count)

Mean of the dataset: -0.028294265399674976
Standard deviation of the dataset: 1.000942073524575
Number of values greater than the mean: 5042

In [ ]:
#Problem 5: Temperature Analysis Using List Comprehensions

# Given list of daily temperatures
temperatures = [32, 35, 38, 29, 31, 28, 27, 35, 30, 31, 29, 33, 34, 36, 37, 38, 39]

# 1. Filter temperatures above 32°C
above_32 = [temp for temp in temperatures if temp > 32]

# 2. Generate a list of tuples containing temperature and classification
temperature_classification = [
    ("Hot", temp) if temp > 35 else ("Warm", temp) if 30 <= temp <= 35 else ("Cool", temp)
    for temp in temperatures
]

# 3. Compute temperature differences from the average
average_temperature = sum(temperatures) / len(temperatures)
temperature_differences = [temp - average_temperature for temp in temperatures]

print("Temperatures above 32°C:", above_32)
print("Temperature classification:", temperature_classification)
print("Temperature differences from average:", temperature_differences)

Temperatures above 32°C: [35, 38, 35, 33, 34, 36, 37, 38, 39]
Temperature classification: [('Warm', 32), ('Warm', 35), ('Hot', 38), ('Cool', 29), ('Warm', 31), ('Cool', 28), ('Cool', 27), ('Warm', 35), ('Warm', 30), ('Warm', 31), ('Cool', 29), ('Warm', 33), ('Warm', 34), ('Hot', 36), ('Hot', 37), ('Hot', 38), ('Hot', 39)]
Temperature differences from average: [-1.058823529411768, 1.941176470588232, 4.941176470588232, -4.058823529411768, -2.058823529411768, -5.058823529411768, -6.058823529411768, 1.941176470588232, -3.058823529411768, -2.058823529411768, -4.058823529411768, -0.05882352941176805, 0.941176470588232, 2.941176470588232, 3.941176470588232, 4.941176470588232, 5.941176470588232]