In [1]:
# Q1: t1.
import pandas as pd
df = pd.read_csv('employees_large.csv')
print(df)

     Name\tAge\tSalary\tDepartment
0             Alice\t25\t45000\tIT
1               Bob\t30\t70000\tHR
2    Charlie\t22\t30000\tMarketing
3        David\t35\t80000\tFinance
4               Eva\t28\t50000\tIT
5   Frank\t40\t120000\tEngineering
6             Grace\t32\t62000\tHR
7     Hannah\t27\t48000\tMarketing
8          Ian\t29\t75000\tFinance
9              Jack\t26\t46000\tIT
10            Karen\t31\t71000\tHR
11         Leo\t38\t85000\tFinance
12      Mona\t23\t32000\tMarketing
13             Nina\t34\t69000\tHR
14  Oscar\t45\t130000\tEngineering
15   Paul\t41\t110000\tEngineering
16       Quinn\t37\t72000\tFinance
17    Rachel\t33\t65000\tMarketing
18            Steve\t39\t90000\tIT
19    Tom\t50\t140000\tEngineering

In [ ]:
# Q1_t2: