In [ ]:
colors = {'black', 'green', 'white', 'blue', 'grey', 'black'}
print(colors)

{'grey', 'black', 'blue', 'green', 'white'}

In [ ]:
# convert a string into a set
string = 'hello'
string_set = set(string)
print(string_set)

{'e', 'l', 'o', 'h'}

In [ ]:
# set of different numbers and a add new numbers
numbers = {1, 2,3, 4, 5}
numbers.add(6)
numbers.add(7)
print(numbers)

{1, 2, 3, 4, 5, 6, 7}

In [ ]:
# Get 5 items from user to store in a set, to display in lower to upper case both
items = set()
for i in range(5):
    item = input("Enter an item: ")
    items.add(item.upper())
    print(items)

Enter an item: 5
{'5'}
Enter an item: 10
{'10', '5'}
Enter an item: 3
{'10', '5', '3'}
Enter an item: 12
{'12', '10', '5', '3'}
Enter an item: 15
{'3', '10', '5', '12', '15'}

In [ ]:
# Write a python program to create a set, then take any item from user to update that set.
set1 = {1, 2, 3, 4, 5}
item = input("Enter an item to update the set: ")
set1.add(item)
print(set1)

Enter an item to update the set: 6
{'6', 1, 2, 3, 4, 5}

In [ ]:
# Write a Python Program to Get 5 Numbers from User to Store in a Set to Find their Addition and Product.
set1 = set()
for i in range (5):
    number = int(input("Enter a number:"))
    set1.add(number)
    print(set1)
    product = 1
    for number in set1:
        product *= number
        print("Addition: ", addition)
        print("Product: ", product)

{5}
Addition:  5
Product:  5
{10, 5}
Addition:  15
Product:  10
Addition:  15
Product:  50
{10, 2, 5}
Addition:  17
Product:  10
Addition:  17
Product:  20
Addition:  17
Product:  100
{3, 10, 2, 5}
Addition:  20
Product:  3
Addition:  20
Product:  30
Addition:  20
Product:  60
Addition:  20
Product:  300
Enter a number:5
{3, 10, 2, 5}
Addition:  20
Product:  3
Addition:  20
Product:  30
Addition:  20
Product:  60
Addition:  20
Product:  300

In [9]:
#
from random import randint
nums = {randint(0, 1000) for i in range (100)}
print(nums)
odd_nums = {x for x in nums if x%2 == 1}
print(odd_nums)

{515, 521, 524, 527, 529, 18, 532, 537, 30, 35, 553, 46, 49, 51, 563, 566, 567, 58, 59, 63, 588, 78, 592, 593, 82, 85, 92, 97, 105, 106, 635, 124, 642, 131, 643, 140, 655, 680, 682, 174, 179, 188, 192, 705, 203, 717, 720, 210, 216, 218, 221, 737, 741, 749, 757, 759, 248, 762, 252, 774, 776, 778, 791, 281, 793, 798, 290, 805, 806, 811, 822, 318, 832, 840, 344, 863, 361, 368, 374, 375, 388, 391, 907, 410, 922, 413, 414, 422, 424, 943, 435, 961, 974, 474, 995, 494, 506}
{515, 131, 643, 391, 521, 907, 527, 655, 529, 791, 537, 281, 793, 413, 35, 805, 553, 811, 943, 49, 51, 563, 179, 435, 567, 59, 63, 705, 961, 203, 717, 593, 85, 221, 863, 375, 97, 737, 995, 741, 105, 361, 749, 757, 759, 635}

In [10]:
# write a python program to get two set from user to find intersection of those set.
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}
intersection = set1.intersection(set2)
print(intersection)

{3, 4, 5}

In [11]:
# write a python program to get two set from user and Check which  Set is Subset of Other?
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}
print(set1.issubset(set2))
print(set2.issubset(set1))

False
False

In [12]:
# Write a Python Program to Create  a Set, User Able to Remove any Element from that Set, then Display Set Element to User, then Add Removed Element to Set, then Display.
set1 = {1, 2, 3, 4, 5}
print(set1)
element = int(input("Enter an element to remove from the set: "))
set1.remove(element)
print(set1)
set1.add(element)
print(set1)

{1, 2, 3, 4, 5}
Enter an element to remove from the set: 3
{1, 2, 4, 5}
{1, 2, 3, 4, 5}

In [14]:
# Write a Python Program to get 5 Students Name from user and Store in Tuple, Display all the Students Name with Uppercase Letters.
students = []
for i in range(5):
    name = input("Enter a student name: ")
    students.append(name.upper())
    print(students)

Enter a student name: ashfak
['ASHFAK']
Enter a student name: refat
['ASHFAK', 'REFAT']
Enter a student name: priyo
['ASHFAK', 'REFAT', 'PRIYO']
Enter a student name: zahid
['ASHFAK', 'REFAT', 'PRIYO', 'ZAHID']
Enter a student name: masud
['ASHFAK', 'REFAT', 'PRIYO', 'ZAHID', 'MASUD']

In [16]:
# Write a Python Program to get 10 Numbers from user, Store in Tuple, and Display only Odd Numbers getting from the Tuple.

numbers = []

for i in range(10):
    num = int(input(f"Enter number {i+1}: "))
    numbers.append(num)

numbers_tuple = tuple(numbers)

print("Odd numbers in the tuple are:")
for num in numbers_tuple:
    if num % 2 != 0:
        print(num)

Enter number 1: 45
Enter number 2: 50
Enter number 3: 55
Enter number 4: 60
Enter number 5: 65
Enter number 6: 70
Enter number 7: 75
Enter number 8: 80
Enter number 9: 85
Enter number 10: 90
Odd numbers in the tuple are:
45
55
65
75
85

In [17]:
from random import randint

nums = [randint(0, 1000) for x in range(10)]
nums = tuple(nums)
print(nums)

odd_nums = tuple([x for x in nums if x % 2 == 1])
print (odd_nums)

(969, 454, 347, 567, 675, 61, 157, 911, 373, 221)
(969, 347, 567, 675, 61, 157, 911, 373, 221)

In [18]:
# Write a Python Program to get 5 any Words from user, Iterate that Tuple to Display only those Word Name that ends with “n”.

words = []

for i in range(5):
    word = input(f"Enter word {i+1}: ")
    words.append(word)

words_tuple = tuple(words)

print("Words that end with 'n' are:")
for word in words_tuple:
    if word.endswith('n'):
        print(word)

Enter word 1: apple
Enter word 2: banana
Enter word 3: cherry
Enter word 4: dragon
Enter word 5: orange
Words that end with 'n' are:
dragon

In [20]:
# Initialize an empty list to store the numbers from the user
numbers = []

for i in range(10):
    num = int(input(f"Enter number {i+1}: "))
    numbers.append(num)

print("Numbers divisible by both 2 and 3 are:")
for num in numbers:
    if num % 2 == 0 and num % 3 == 0:

        print(num)

Enter number 1: 1
Enter number 2: 3
Enter number 3: 4
Enter number 4: 5
Enter number 5: 2
Enter number 6: 8
Enter number 7: 9
Enter number 8: 7
Enter number 9: 6
Enter number 10: 0
Numbers divisible by both 2 and 3 are:
6
0